language: php
php:
  - 5.4
  - hhvm
env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.6.*"
  - LOWEST=1
before_script:
  - composer self-update
  - if [ ! -z $SYMFONY_VERSION ]; then composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist; fi
  - if [ ! -z $LOWEST ]; then composer update --prefer-dist --prefer-lowest; fi
script:
  # - phpunit -c phpunit.dist.xml
  - php ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php ./vendor/bin/coveralls -v
matrix:
  # Build with PHP 5.5 and Symfony LTS
  include:
    - php: 5.5
      env: SYMFONY_VERSION="2.3.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*@dev"

  exclude:
    - php: hhvm
      env: LOWEST=1

  # Test the latest PHP and Symfony Next
  allow_failures:
    - env: SYMFONY_VERSION="2.7.*@dev"
    - php: hhvm

  fast_finish: true

notifications:
  email:
    - dev@dankempster.co.uk

branches:
  only:
    - develop
    - master
